import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Testimonials from '../components/Testimonials'
import styles from '../styles/Home.module.css'

export default function Home({darkMode, setDarkMode, handleDarkMode}) {
  return (
    <div className={darkMode ? " w-screen h-fit bg-gray-800 text-white" : " w-screen h-fit"}>
      <Head>
        <title>Adv Rajan Ladkat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero darkMode={darkMode} setDarkMode={setDarkMode} />
      <hr className={darkMode ? "hidden" : "border-2 border-b-blue-500 w-1/2 mx-auto"} />
      <Testimonials darkMode={darkMode} />
    </div>
  )
}
